fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.3.0"
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-no-eval
      - id: python-check-blanket-type-ignore
      - id: python-check-blanket-noqa
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # ruff - linting + formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.1"
    hooks:
      - id: ruff
        name: ruff
      - id: ruff-format
        name: ruff-format

  # mypy - lint-like type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy

  # bandit - find common security issues
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r
          - src

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests #--cov=app
        language: system
        types: [python]
        pass_filenames: false

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^uv.lock
